# Generated by Django 3.2 on 2022-10-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='question',
        #     name='title',
        # ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.question'),
        ),
    ]
