# Generated by Django 3.2 on 2022-10-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_remove_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
