# Generated by Django 3.2 on 2023-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20221012_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_published_answer',
            field=models.BooleanField(default=False),
        ),
    ]
