# Generated by Django 3.2 on 2023-02-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_question_has_published_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_published_answer',
        ),
    ]
