# Generated by Django 3.2 on 2022-10-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_answer_question'),
        ('faq', '0006_auto_20221006_1507'),
    ]

    operations = [
    ]
