# Generated by Django 3.2 on 2022-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
