# Generated by Django 3.2 on 2022-10-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_email_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_answer',
        ),
    ]
