# Generated by Django 3.2 on 2022-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
