# Generated by Django 3.2 on 2022-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20221009_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email_on_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
