# Generated by Django 3.2 on 2022-10-12 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0003_question_email_on_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='email_on_answer',
            field=models.BooleanField(default=0),
        ),
    ]
