# Generated by Django 3.2 on 2023-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_on_answer',
            field=models.BooleanField(default=False),
        ),
    ]
