# Generated by Django 3.2 on 2023-03-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_email_on_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_on_answer',
            new_name='newsletter_signup',
        ),
    ]
