# Generated by Django 3.2 on 2022-10-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        # migrations.AlterField(
        #     model_name='product',
        #     name='category',
        #     field=models.ForeignKey(default='To Be Added', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category'),
        # ),
    ]
