# Generated by Django 3.2 on 2022-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_fake_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fake',
            name='description',
            field=models.TextField(default='None yet'),
        ),
        migrations.AddField(
            model_name='fake',
            name='image',
            field=models.ImageField(default='None yet', upload_to='media/product_images'),
        ),
        migrations.AddField(
            model_name='fake',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fake',
            name='short_description',
            field=models.TextField(default='None yet'),
        ),
    ]
