# Generated by Django 3.2 on 2023-01-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fake',
        ),
    ]
